import { orb09Shader } from "@/components/orbs/orb-09/gpu";
import type { OrbVariant } from "@/components/orbs/orbkit-core-wgpu";

export const meta = {
  description: "torn rings of rainbow light worn as the ball's latitudes",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-09",
  title: "ORB-09",
} as const;

export const orb09Orb: OrbVariant = {
  colors: [
    { default: "#ffffff", key: "tint", label: "Tint" },
    { default: "#b9d6ff", key: "sheen", label: "Sheen" },
  ],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.6,
      integrate: true,
      key: "speed",
      label: "Anim speed",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0.12,
      integrate: true,
      key: "spin",
      label: "Roll",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0.4,
      key: "tilt",
      label: "Tilt",
      max: 1.5,
      min: -1.5,
      step: 0.015,
    },
    {
      default: 0.9,
      key: "radius",
      label: "Radius",
      max: 3,
      min: 0.15,
      step: 0.015,
    },
    {
      default: 3.5,
      key: "scale",
      label: "Ring spacing",
      max: 20,
      min: 0.3,
      step: 0.1,
    },
    { default: 0.45, key: "warp", label: "Tear", max: 3, min: 0, step: 0.02 },
    {
      default: 0.9,
      key: "seed",
      label: "Ring seed",
      max: 3,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.05,
      key: "glow",
      label: "Ring glow",
      max: 1,
      min: 0,
      step: 0.002,
    },
    {
      default: 0.05,
      key: "lineSoft",
      label: "Ring width",
      max: 1,
      min: 0.002,
      step: 0.002,
    },
    {
      default: 3,
      key: "inner",
      label: "Inner falloff",
      max: 12,
      min: 0.2,
      step: 0.05,
    },
    {
      default: 0.1,
      key: "fringe",
      label: "Rainbow fringe",
      max: 2,
      min: 0,
      step: 0.005,
    },
    {
      default: 0.003,
      key: "fringeSoft",
      label: "Fringe width",
      max: 1,
      min: 0.001,
      step: 0.001,
    },
    {
      default: 0.8,
      key: "ringPhase",
      label: "Ring hue step",
      max: 3,
      min: 0,
      step: 0.01,
    },
    {
      default: 1.1,
      key: "exposure",
      label: "Exposure",
      max: 20,
      min: 0.05,
      step: 0.05,
    },
    {
      default: 1.1,
      key: "contrast",
      label: "Contrast",
      max: 10,
      min: 0.15,
      step: 0.05,
    },
    {
      default: 1.2,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 0.5,
      key: "light",
      label: "Key light",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0.4,
      key: "rim",
      label: "Rim sheen",
      max: 3,
      min: 0,
      step: 0.015,
    },
  ],
  shader: orb09Shader,
  stateColors: {
    idle: { sheen: "#b9d6ff", tint: "#ffffff" },
    speaking: { sheen: "#ffb277", tint: "#ffc492" },
    thinking: { sheen: "#7ba6ff", tint: "#9db8ff" },
  },

  statePresets: {
    idle: {
      contrast: 1.15,
      exposure: 1.1,
      fringe: 0.1,
      glow: 0.05,
      lineSoft: 0.05,
      speed: 0.6,
      spin: 0.12,
      warp: 0.45,
    },
    speaking: {
      contrast: 0.85,
      exposure: 0.68,
      fringe: 0.81,
      fringeSoft: 0.058,
      glow: 0.04,
      light: 0.99,
      lineSoft: 0.22,
      rim: 0.015,
      ringPhase: 1.03,
      seed: 1.02,
      speed: 4.7,
      spin: 0.34,
      warp: 0.22,
    },
    thinking: {
      contrast: 1.15,
      exposure: 1.75,
      fringe: 0.96,
      fringeSoft: 0.854,
      glow: 0.2,
      light: 1.035,
      lineSoft: 0.152,
      rim: 0.66,
      ringPhase: 2.53,
      saturation: 2.22,
      warp: 2.54,
    },
  },
};
