import type { OrbVariant } from "@/components/orbs/canvas";
import { orb07Params, orb07Shader } from "@/components/orbs/orb-07/gpu";

export const meta = {
  description:
    "a twist wave travelling out through the ball around a lit column",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-07",
  title: "ORB-07",
} as const;

export const orb07Orb: OrbVariant = {
  colors: [{ default: "#ffffff", key: "tint", label: "Tint" }],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.5,
      integrate: true,
      key: "speed",
      label: "Cell shimmer",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0.7,
      integrate: true,
      key: "wave",
      label: "Wave speed",
      max: 8,
      min: 0,
      step: 0.03,
    },
    { default: 1, key: "twist", label: "Twist", max: 8, min: 0, step: 0.02 },
    {
      default: 0.1,
      integrate: true,
      key: "spin",
      label: "Roll",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0.3,
      key: "tilt",
      label: "Axis lean",
      max: 1.5,
      min: -1.5,
      step: 0.015,
    },
    {
      default: 7,
      key: "camDist",
      label: "Camera distance",
      max: 50,
      min: 1,
      step: 0.3,
    },
    {
      default: 2.25,
      key: "focal",
      label: "Lens",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 1,
      key: "turb",
      label: "Cell turbulence",
      max: 5,
      min: 0,
      step: 0.03,
    },
    {
      default: 0,
      key: "column",
      label: "Column release",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.1,
      key: "stepScale",
      label: "Step scale",
      max: 1.5,
      min: 0.005,
      step: 0.005,
    },
    {
      default: 0.75,
      key: "hueDepth",
      label: "Depth hue",
      max: 10,
      min: 0,
      step: 0.03,
    },
    {
      default: 0.45,
      key: "hueStep",
      label: "Step hue",
      max: 10,
      min: 0,
      step: 0.03,
    },
    {
      default: 2.6,
      key: "envRadius",
      label: "Envelope radius",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 0.88,
      key: "envCore",
      label: "Envelope core",
      max: 1.02,
      min: 0.3,
      step: 0.01,
    },
    {
      default: 0.15,
      key: "fill",
      label: "Body fill",
      max: 100,
      min: 0,
      step: 0.3,
    },
    {
      default: 400,
      key: "stepClamp",
      label: "Step clamp",
      max: 5000,
      min: 3,
      step: 10,
    },
    {
      default: 0.01,
      key: "scatter",
      label: "Diffusion",
      max: 0.5,
      min: 0,
      step: 0.003,
    },
    {
      default: 60,
      key: "exposure",
      label: "Exposure",
      max: 5000,
      min: 1.5,
      step: 5,
    },
    {
      default: 1.3,
      key: "contrast",
      label: "Contrast",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 1.15,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 2,
      key: "alphaGain",
      label: "Alpha gain",
      max: 15,
      min: 0.05,
      step: 0.1,
    },
    {
      default: 1,
      key: "edge",
      label: "Edge sharpness",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.98,
      key: "edgeFade",
      label: "Halo falloff",
      max: 3,
      min: 0.1,
      step: 0.015,
    },
  ],
  shader: orb07Shader,
  stateColors: {
    idle: { tint: "#ffffff" },
    speaking: { tint: "#ffc492" },
    thinking: { tint: "#9db8ff" },
  },

  statePresets: {
    idle: {
      alphaGain: 2,
      column: 0,
      exposure: 60,
      scatter: 0.01,
      speed: 0.5,
      turb: 1,
      twist: 1,
      wave: 0.7,
    },
    speaking: {
      alphaGain: 2.7,
      column: 0.45,
      exposure: 26,
      scatter: 0.006,
      speed: 0.9,
      turb: 0.85,
      twist: 0.35,
      wave: 3.2,
    },
    thinking: {
      alphaGain: 2,
      column: 0,
      exposure: 88,
      scatter: 0.011,
      speed: 1.5,
      turb: 1.35,
      twist: 3.6,
      wave: 0.15,
    },
  },
  uniforms: orb07Params,
};
