import { orb08Shader } from "@/components/orbs/orb-08/gpu";
import type { OrbVariant } from "@/components/orbs/orbkit-core-wgpu";

export const meta = {
  description: "mother-of-pearl contour bands, each layer its own hue",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-08",
  title: "ORB-08",
} as const;

export const orb08Orb: OrbVariant = {
  colors: [
    { default: "#0d1430", key: "deep", label: "Shell body" },
    { default: "#2fb8c6", key: "low", label: "Dim layer" },
    { default: "#fff1de", key: "crest", label: "Bright layer" },
    { default: "#bfe4ff", key: "sheen", label: "Sheen" },
  ],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.35,
      integrate: true,
      key: "speed",
      label: "Boil",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0.25,
      integrate: true,
      key: "flow",
      label: "Band drift",
      max: 5,
      min: 0,
      step: 0.03,
    },
    {
      default: 0.06,
      integrate: true,
      key: "swirl",
      label: "Swirl",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0.9,
      key: "radius",
      label: "Radius",
      max: 3,
      min: 0.15,
      step: 0.015,
    },
    {
      default: 5.5,
      key: "scale",
      label: "Pattern scale",
      max: 20,
      min: 0.3,
      step: 0.1,
    },
    {
      default: 0.3,
      key: "bulge",
      label: "Dome bulge",
      max: 4,
      min: 0,
      step: 0.02,
    },
    { default: 1, key: "warp", label: "Warp", max: 3, min: 0, step: 0.02 },
    { default: 0, key: "beat", label: "Warp beat", max: 1, min: 0, step: 0.01 },
    {
      default: 0.2,
      key: "thick",
      label: "Band width",
      max: 2,
      min: 0.02,
      step: 0.01,
    },
    {
      default: 0.1,
      key: "split",
      label: "Chromatic split",
      max: 1,
      min: 0,
      step: 0.005,
    },
    {
      default: 0.7,
      key: "iris",
      label: "Iridescence",
      max: 2,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.315,
      key: "irisScale",
      label: "Iridescence scale",
      max: 2,
      min: 0,
      step: 0.005,
    },
    {
      default: 1.34,
      key: "view",
      label: "Angle shift",
      max: 3,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.8,
      key: "floor",
      label: "Body fill",
      max: 3,
      min: 0,
      step: 0.01,
    },
    {
      default: 1.1,
      key: "gain",
      label: "Brightness",
      max: 5,
      min: 0.05,
      step: 0.05,
    },
    {
      default: 1.15,
      key: "contrast",
      label: "Contrast",
      max: 10,
      min: 0.15,
      step: 0.05,
    },
    {
      default: 0.75,
      key: "light",
      label: "Key light",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0.5,
      key: "rim",
      label: "Rim sheen",
      max: 3,
      min: 0,
      step: 0.015,
    },
  ],
  shader: orb08Shader,
  stateColors: {
    idle: {
      crest: "#fff1de",
      deep: "#0d1430",
      low: "#2fb8c6",
      sheen: "#bfe4ff",
    },
    speaking: {
      crest: "#fff0c9",
      deep: "#2a0f22",
      low: "#ff7a4d",
      sheen: "#ffc9a8",
    },
    thinking: {
      crest: "#dfe8ff",
      deep: "#0a0f2c",
      low: "#6f7cff",
      sheen: "#9fd0ff",
    },
  },

  statePresets: {
    idle: {
      bulge: 0.8,
      contrast: 1.65,
      floor: 0.57,
      flow: 0.24,
      gain: 2.45,
      iris: 1.02,
      rim: 0.495,
      speed: 0.37,
      split: 0.1,
      swirl: 0.06,
      thick: 0.54,
      warp: 0.96,
    },
    speaking: {
      beat: 1,
      contrast: 0.78,
      flow: 2.49,
      gain: 1.75,
      iris: 0.45,
      speed: 2,
      split: 0.3,
      swirl: 0.18,
      thick: 0.27,
      warp: 1.84,
    },
    thinking: {
      contrast: 1.65,
      floor: 0.77,
      flow: 0.06,
      gain: 0.85,
      iris: 1.89,
      irisScale: 0.26,
      rim: 0.495,
      speed: 1.61,
      split: 0.3,
      swirl: 0.015,
      thick: 0.54,
      view: 1.21,
      warp: 1.56,
    },
  },
};
