export const ROUTES = {
  AGENT_SKILLS_INDEX: "/.well-known/agent-skills/index.json",
  AGENT_SKILLS_SITE_SKILL: "/.well-known/agent-skills/site-skill.md",
  API_CATALOG: "/.well-known/api-catalog",
  API_STATUS: "/api/status",
  DOCS: "/docs",
  DOCS_COMPONENTS: "/docs/components",
  DOCS_INSTALLATION: "/docs/installation",
  HOME: "/",
  LLMS: "/llms.txt",
  LLMS_FULL: "/llms-full.txt",
  LLMS_MD: "/llms.md",
  MANIFEST: "/manifest.webmanifest",
  MCP: "/mcp",
  OPENAPI: "/openapi.json",
  PLAYGROUND: "/playground",
  REGISTRY: "/r/registry.json",
  ROBOTS: "/robots.txt",
  RSS: "/rss.xml",
  SITEMAP: "/sitemap.xml",
  SPONSOR: "/sponsor",
  VGPU_DOCS: "https://vgpu.labs.vercel.dev/docs",
  VGPU_GITHUB: "https://github.com/vercel-labs/vgpu",
} as const;
