import type { OrbVariant } from "@/components/orbs/canvas";
import { orb06Shader } from "@/components/orbs/orb-06/gpu";

export const meta = {
  description:
    "a hundred glowing lattices stacked through the ball, interfering",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-06",
  title: "ORB-06",
} as const;

export const orb06Orb: OrbVariant = {
  colors: [
    { default: "#ffffff", key: "tint", label: "Tint" },
    { default: "#bcd8ff", key: "sheen", label: "Sheen" },
  ],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.5,
      integrate: true,
      key: "speed",
      label: "Anim speed",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0.02,
      key: "drift",
      label: "Layer walk",
      max: 0.3,
      min: 0,
      step: 0.002,
    },
    {
      default: 0.9,
      key: "radius",
      label: "Radius",
      max: 3,
      min: 0.15,
      step: 0.015,
    },
    {
      default: 4,
      key: "scale",
      label: "Pattern scale",
      max: 20,
      min: 0.3,
      step: 0.1,
    },
    {
      default: 0.3,
      key: "bulge",
      label: "Dome bulge",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 0.7,
      key: "depth",
      label: "Stack depth",
      max: 1.6,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.7,
      key: "freq",
      label: "Lattice spacing",
      max: 5,
      min: 0.05,
      step: 0.01,
    },
    {
      default: 0.05,
      key: "glowSize",
      label: "Glow size",
      max: 1,
      min: 0.002,
      step: 0.002,
    },
    {
      default: 0.037,
      key: "hueRate",
      label: "Hue per layer",
      max: 0.5,
      min: 0,
      step: 0.002,
    },
    {
      default: 4,
      key: "exposure",
      label: "Exposure",
      max: 200,
      min: 0.05,
      step: 0.05,
    },
    {
      default: 1.1,
      key: "contrast",
      label: "Contrast",
      max: 10,
      min: 0.15,
      step: 0.05,
    },
    {
      default: 1.2,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 0.45,
      key: "light",
      label: "Key light",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0.4,
      key: "rim",
      label: "Rim sheen",
      max: 3,
      min: 0,
      step: 0.015,
    },
  ],
  shader: orb06Shader,
  stateColors: {
    idle: { sheen: "#bcd8ff", tint: "#ffffff" },
    speaking: { sheen: "#ffb277", tint: "#ffc492" },
    thinking: { sheen: "#7ea9ff", tint: "#9db8ff" },
  },
  statePresets: {
    idle: {
      contrast: 1.1,
      depth: 0.7,
      drift: 0.02,
      exposure: 4,
      glowSize: 0.05,
      hueRate: 0.037,
      speed: 0.5,
    },
    speaking: {
      contrast: 0.9,
      depth: 0.26,
      drift: 0.13,
      exposure: 2.7,
      glowSize: 0.062,
      hueRate: 0.045,
      light: 1.11,
      speed: 4.5,
    },
    thinking: {
      bulge: 2.18,
      contrast: 1.55,
      depth: 1.25,
      drift: 0.105,
      exposure: 6.5,
      glowSize: 0.016,
      hueRate: 0.095,
      speed: 2.6,
    },
  },
};
