import { orb01Shader } from "@/components/orbs/orb-01/gpu";
import type { OrbVariant } from "@/components/orbs/orbkit-core-wgpu";

export const meta = {
  description: "cut-glass orb with a dispersive, turbulent interior",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-01",
  title: "ORB-01",
} as const;

export const orb01Orb: OrbVariant = {
  colors: [{ default: "#ffffff", key: "tint", label: "Tint" }],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.5,
      integrate: true,
      key: "speed",
      label: "Anim speed",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0.25,
      integrate: true,
      key: "spin",
      label: "Spin rate",
      max: 5,
      min: 0,
      step: 0.03,
    },
    {
      default: 7,
      key: "camDist",
      label: "Camera distance",
      max: 50,
      min: 1,
      step: 0.3,
    },
    {
      default: 2.25,
      key: "focal",
      label: "Lens",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 0.5,
      key: "tilt",
      label: "Field tilt",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 0.3,
      key: "turb",
      label: "Turbulence",
      max: 5,
      min: 0,
      step: 0.03,
    },
    {
      default: 7,
      key: "sheets",
      label: "Sheet density",
      max: 60,
      min: 1,
      step: 0.5,
    },
    {
      default: 1,
      key: "disperse",
      label: "Dispersion",
      max: 5,
      min: 0,
      step: 0.03,
    },
    {
      default: 1,
      key: "stria",
      label: "Striation depth",
      max: 10,
      min: 0,
      step: 0.05,
    },
    {
      default: 2.6,
      key: "envRadius",
      label: "Envelope radius",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 1,
      key: "envCore",
      label: "Envelope core",
      max: 1.02,
      min: 0.3,
      step: 0.01,
    },
    {
      default: 1.5,
      key: "fill",
      label: "Body fill",
      max: 100,
      min: 0,
      step: 0.3,
    },
    {
      default: 20,
      key: "stepClamp",
      label: "Step clamp",
      max: 300,
      min: 0.3,
      step: 1.5,
    },
    {
      default: 0.02,
      key: "scatter",
      label: "Diffusion",
      max: 0.5,
      min: 0,
      step: 0.003,
    },
    {
      default: 60,
      key: "exposure",
      label: "Exposure",
      max: 1500,
      min: 1.5,
      step: 10,
    },
    {
      default: 1,
      key: "contrast",
      label: "Contrast",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 1,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 2,
      key: "alphaGain",
      label: "Alpha gain",
      max: 15,
      min: 0.05,
      step: 0.1,
    },
    {
      default: 1,
      key: "edge",
      label: "Edge sharpness",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.98,
      key: "edgeFade",
      label: "Halo falloff",
      max: 3,
      min: 0.1,
      step: 0.015,
    },
  ],
  shader: orb01Shader,
  statePresets: {
    idle: {
      alphaGain: 2,
      disperse: 1,
      exposure: 60,
      scatter: 0.02,
      sheets: 7,
      speed: 0.5,
      spin: 0.25,
      turb: 0.3,
    },
    speaking: {
      alphaGain: 2.5,
      disperse: 1.5,
      exposure: 45,
      scatter: 0.015,
      sheets: 5.5,
      speed: 1.2,
      spin: 0.7,
      turb: 0.55,
    },
    thinking: {
      alphaGain: 2.1,
      disperse: 1.1,
      exposure: 57,
      scatter: 0.019,
      sheets: 7,
      speed: 0.6,
      spin: 0.5,
      turb: 0.35,
    },
  },
};
