import type { OrbVariant } from "@/components/orbs/canvas";
import { orb22Shader } from "@/components/orbs/orb-22/gpu";

export const meta = {
  description: "field lines swirling around the ball about a wandering axis",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-22",
  title: "ORB-22",
} as const;

export const orb22Orb: OrbVariant = {
  colors: [{ default: "#ffffff", key: "tint", label: "Tint" }],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.5,
      integrate: true,
      key: "speed",
      label: "Anim speed",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0.12,
      integrate: true,
      key: "wander",
      label: "Axis wander",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 7,
      key: "camDist",
      label: "Camera distance",
      max: 50,
      min: 1,
      step: 0.3,
    },
    {
      default: 2.25,
      key: "focal",
      label: "Lens",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 0.8,
      key: "hug",
      label: "Surface hug",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0.6,
      key: "turb",
      label: "Cell shimmer",
      max: 5,
      min: 0,
      step: 0.03,
    },
    {
      default: 0.07,
      key: "stepScale",
      label: "Step scale",
      max: 1.5,
      min: 0.005,
      step: 0.01,
    },
    {
      default: 0.12,
      key: "hueStep",
      label: "Step hue",
      max: 10,
      min: 0,
      step: 0.03,
    },
    {
      default: 1.4,
      key: "hueDepth",
      label: "Depth hue",
      max: 10,
      min: 0,
      step: 0.03,
    },
    {
      default: 1.4,
      key: "glow",
      label: "Vector glow",
      max: 10,
      min: 0,
      step: 0.05,
    },
    {
      default: 0.12,
      key: "glowFew",
      label: "Glow density",
      max: 1.5,
      min: 0,
      step: 0.01,
    },
    {
      default: 2.6,
      key: "envRadius",
      label: "Envelope radius",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 0.88,
      key: "envCore",
      label: "Envelope core",
      max: 1.02,
      min: 0.3,
      step: 0.01,
    },
    {
      default: 0.15,
      key: "fill",
      label: "Body fill",
      max: 100,
      min: 0,
      step: 0.3,
    },
    {
      default: 800,
      key: "stepClamp",
      label: "Step clamp",
      max: 5000,
      min: 3,
      step: 30,
    },
    {
      default: 0.01,
      key: "scatter",
      label: "Diffusion",
      max: 0.5,
      min: 0,
      step: 0.003,
    },
    {
      default: 260,
      key: "exposure",
      label: "Exposure",
      max: 5000,
      min: 1.5,
      step: 15,
    },
    {
      default: 1.3,
      key: "contrast",
      label: "Contrast",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 1.15,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 2,
      key: "alphaGain",
      label: "Alpha gain",
      max: 15,
      min: 0.05,
      step: 0.1,
    },
    {
      default: 1,
      key: "edge",
      label: "Edge sharpness",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.98,
      key: "edgeFade",
      label: "Halo falloff",
      max: 3,
      min: 0.1,
      step: 0.015,
    },
  ],
  // the tint carries the at-a-glance read, as in chords: neutral at rest,
  // cooled while searching, warmed while answering
  shader: orb22Shader,
  stateColors: {
    idle: { tint: "#ffffff" },
    speaking: { tint: "#ffd9c4" },
    thinking: { tint: "#c3d2ff" },
  },
  /*
    The states are staged on this orb's two best levers, both phase-safe
    integrated clocks: the AXIS WANDER (the whole field re-orients as the
    axis moves) and the cell-flicker speed. glowFew is the third lever —
    how many of the hot-wire vectors are lit at once.
  */
  statePresets: {
    idle: {
      alphaGain: 2,
      exposure: 260,
      glow: 1.3,
      glowFew: 0.12,
      scatter: 0.01,
      speed: 0.4,
      turb: 0.55,
      wander: 0.1,
    },
    speaking: {
      alphaGain: 2.5,
      exposure: 170,
      glow: 2.4,
      glowFew: 0.22,
      scatter: 0.0075,
      speed: 2.2,
      turb: 0.85,
      wander: 0.3,
    },
    thinking: {
      alphaGain: 2.1,
      exposure: 230,
      glow: 1.7,
      glowFew: 0.07,
      scatter: 0.0095,
      speed: 1.2,
      turb: 0.7,
      wander: 0.6,
    },
  },
};
