import { orb03Shader } from "@/components/orbs/orb-03/gpu";
import type { OrbVariant } from "@/components/orbs/orbkit-core-wgpu";

export const meta = {
  description:
    "a turbulent belt of light girdling the ball, contoured in rainbow",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-03",
  title: "ORB-03",
} as const;

export const orb03Orb: OrbVariant = {
  colors: [{ default: "#ffffff", key: "tint", label: "Tint" }],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.6,
      integrate: true,
      key: "speed",
      label: "Anim speed",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0.3,
      integrate: true,
      key: "wander",
      label: "Belt tilt drift",
      max: 5,
      min: 0,
      step: 0.02,
    },
    {
      default: 1.5,
      key: "feedback",
      label: "Tilt feedback",
      max: 40,
      min: 0,
      step: 0.1,
    },
    {
      default: 5,
      key: "camDist",
      label: "Camera distance",
      max: 50,
      min: 1,
      step: 0.3,
    },
    {
      default: 1.05,
      key: "focal",
      label: "Lens",
      max: 15,
      min: 0.15,
      step: 0.05,
    },
    {
      default: 3,
      key: "shellR",
      label: "Shell radius",
      max: 20,
      min: 0.2,
      step: 0.1,
    },
    {
      default: 0.12,
      key: "shellW",
      label: "Shell weight",
      max: 1,
      min: 0.005,
      step: 0.005,
    },
    {
      default: 0.15,
      key: "plane",
      label: "Belt tightness",
      max: 1,
      min: 0,
      step: 0.005,
    },
    { default: 0.55, key: "turb", label: "Warp", max: 4, min: 0, step: 0.02 },
    {
      default: 0.004,
      key: "width",
      label: "Belt width",
      max: 0.4,
      min: 0.0005,
      step: 0.0005,
    },
    {
      default: 0,
      key: "pulse",
      label: "Belt breathing",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0,
      key: "surge",
      label: "Belt surge",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 25,
      key: "hue",
      label: "Contour hue",
      max: 60,
      min: 0,
      step: 0.1,
    },
    {
      default: 1,
      key: "spread",
      label: "Colour spread",
      max: 3,
      min: 0,
      step: 0.02,
    },
    {
      default: 3.3,
      key: "envRadius",
      label: "Envelope radius",
      max: 20,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 0.92,
      key: "envCore",
      label: "Envelope core",
      max: 1.02,
      min: 0.3,
      step: 0.01,
    },
    {
      default: 0.1,
      key: "fill",
      label: "Body fill",
      max: 40,
      min: 0,
      step: 0.05,
    },
    {
      default: 1500,
      key: "stepClamp",
      label: "Step clamp",
      max: 20_000,
      min: 5,
      step: 25,
    },
    {
      default: 0.0006,
      key: "scatter",
      label: "Diffusion",
      max: 0.1,
      min: 0,
      step: 0.0002,
    },
    {
      default: 1500,
      key: "exposure",
      label: "Exposure",
      max: 100_000,
      min: 20,
      step: 50,
    },
    {
      default: 1.2,
      key: "contrast",
      label: "Contrast",
      max: 15,
      min: 0.15,
      step: 0.05,
    },
    {
      default: 1.25,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 2,
      key: "alphaGain",
      label: "Alpha gain",
      max: 15,
      min: 0.05,
      step: 0.1,
    },
    {
      default: 1,
      key: "edge",
      label: "Edge sharpness",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.98,
      key: "edgeFade",
      label: "Halo falloff",
      max: 3,
      min: 0.1,
      step: 0.015,
    },
  ],
  // the contour ramp supplies the colour, so the tint only shifts its
  // temperature: neutral at rest, cooled while searching, warmed while
  // answering
  shader: orb03Shader,
  stateColors: {
    idle: { tint: "#ffffff" },
    speaking: { tint: "#ffc492" },
    thinking: { tint: "#9db8ff" },
  },
  /*
    Staged on BELT TIGHTNESS, which is the only control that changes what
    the object is: high and the light is a single girdle, low and it opens
    out into the whole shell. Warp and belt width carry the rest.
  */
  statePresets: {
    idle: {
      alphaGain: 2,
      envCore: 1.02,
      exposure: 1450,
      feedback: 2,
      hue: 39.8,
      plane: 0.085,
      scatter: 0.0006,
      shellR: 2,
      shellW: 0.085,
      speed: 0.6,
      spread: 0.94,
      stepClamp: 1475,
      turb: 1.54,
      wander: 0.3,
      width: 0.001,
    },
    speaking: {
      alphaGain: 2.7,
      envRadius: 3.4,
      exposure: 650,
      feedback: 0.3,
      plane: 0.1,
      scatter: 0.0003,
      shellR: 1.8,
      shellW: 0.19,
      speed: 0.9,
      spread: 1.04,
      surge: 1,
      turb: 0.14,
      wander: 0.84,
      width: 0.018,
    },
    thinking: {
      alphaGain: 2,
      envCore: 0.84,
      envRadius: 7.4,
      exposure: 2300,
      feedback: 7.5,
      focal: 1.9,
      hue: 28.3,
      plane: 0.345,
      pulse: 1,
      scatter: 0,
      shellR: 1.9,
      shellW: 0.005,
      speed: 2,
      spread: 1.02,
      turb: 0.7,
      wander: 1.1,
      width: 0.048,
    },
  },
};
