import type { OrbVariant } from "@/components/orbs/canvas";
import { orb20Params, orb20Shader } from "@/components/orbs/orb-20/gpu";

export const meta = {
  description: "a water film rushing down the ball, fountain-style",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-20",
  title: "ORB-20",
} as const;

export const orb20Orb: OrbVariant = {
  colors: [{ default: "#ffffff", key: "tint", label: "Tint" }],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.5,
      integrate: true,
      key: "speed",
      label: "Ripple speed",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 3,
      integrate: true,
      key: "flow",
      label: "Fall rush",
      max: 20,
      min: 0,
      step: 0.1,
    },
    {
      default: 7,
      key: "camDist",
      label: "Camera distance",
      max: 50,
      min: 1,
      step: 0.3,
    },
    {
      default: 2.25,
      key: "focal",
      label: "Lens",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 0.15,
      key: "tilt",
      label: "Flow tilt",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 0.3,
      key: "stretch",
      label: "Fall stretch",
      max: 3,
      min: 0.03,
      step: 0.015,
    },
    { default: 0.3, key: "foam", label: "Foam", max: 3, min: 0, step: 0.015 },
    {
      default: 3,
      key: "wall",
      label: "Film sharpness",
      max: 20,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 0.2,
      key: "stepScale",
      label: "Step scale",
      max: 1.5,
      min: 0.015,
      step: 0.01,
    },
    {
      default: 0.85,
      key: "hueScale",
      label: "Hue banding",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 2.6,
      key: "envRadius",
      label: "Envelope radius",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 1,
      key: "envCore",
      label: "Envelope core",
      max: 1.02,
      min: 0.3,
      step: 0.01,
    },
    {
      default: 0.4,
      key: "fill",
      label: "Body fill",
      max: 100,
      min: 0,
      step: 0.3,
    },
    {
      default: 20,
      key: "stepClamp",
      label: "Step clamp",
      max: 300,
      min: 0.3,
      step: 1.5,
    },
    {
      default: 0.01,
      key: "scatter",
      label: "Diffusion",
      max: 0.5,
      min: 0,
      step: 0.003,
    },
    {
      default: 22,
      key: "exposure",
      label: "Exposure",
      max: 1500,
      min: 1.5,
      step: 10,
    },
    {
      default: 1.15,
      key: "contrast",
      label: "Contrast",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 1.55,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 2,
      key: "alphaGain",
      label: "Alpha gain",
      max: 15,
      min: 0.05,
      step: 0.1,
    },
    {
      default: 1,
      key: "edge",
      label: "Edge sharpness",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.98,
      key: "edgeFade",
      label: "Halo falloff",
      max: 3,
      min: 0.1,
      step: 0.015,
    },
  ],
  shader: orb20Shader,
  statePresets: {
    idle: {
      alphaGain: 2,
      exposure: 22,
      flow: 3,
      foam: 0.3,
      scatter: 0.01,
      speed: 0.5,
    },
    speaking: {
      alphaGain: 2.5,
      exposure: 16,
      flow: 5.5,
      foam: 0.45,
      scatter: 0.0075,
      speed: 1,
    },
    thinking: {
      alphaGain: 2.1,
      exposure: 21,
      flow: 3.3,
      foam: 0.33,
      scatter: 0.0095,
      speed: 0.6,
    },
  },
  uniforms: orb20Params,
};
