import type { OrbVariant } from "@/components/orbs/canvas";
import { orb31Shader } from "@/components/orbs/orb-31/gpu";

export const meta = {
  description: "raymarched shell, volumetric godrays",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-31",
  title: "ORB-31",
} as const;

export const orb31Orb: OrbVariant = {
  colors: [],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 1,
      integrate: true,
      key: "speed",
      label: "Anim speed",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0.5,
      integrate: true,
      key: "sweepRate",
      label: "Sweep rate",
      max: 6,
      min: 0,
      step: 0.02,
    },
    {
      default: 2.6,
      key: "radius",
      label: "Shell radius",
      max: 10,
      min: 0.4,
      step: 0.05,
    },
    {
      default: 0.18,
      key: "swell",
      label: "Input swell",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0.9,
      key: "warp",
      label: "Warp divisor",
      max: 10,
      min: 0.3,
      step: 0.05,
    },
    {
      default: 5.25,
      key: "warpFreq",
      label: "Warp frequency",
      max: 30,
      min: 0.15,
      step: 0.15,
    },
    {
      default: 0,
      key: "warpSwing",
      label: "Warp swing",
      max: 8,
      min: 0,
      step: 0.05,
    },
    {
      default: 0,
      key: "freqSwing",
      label: "Frequency swing",
      max: 15,
      min: 0,
      step: 0.05,
    },
    {
      default: 0,
      key: "smoothSwing",
      label: "Softness swing",
      max: 2,
      min: 0,
      step: 0.005,
    },
    {
      default: 0.42,
      key: "smoothK",
      label: "Blend softness",
      max: 4,
      min: 0.015,
      step: 0.02,
    },
    {
      default: 0.8,
      key: "rayGain",
      label: "Godray gain",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 10.5,
      key: "rayFalloff",
      label: "Godray falloff",
      max: 100,
      min: 0.3,
      step: 0.5,
    },
    {
      default: 0.105,
      key: "surfaceLit",
      label: "Surface light",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0,
      key: "ambient",
      label: "Ambient",
      max: 1,
      min: 0,
      step: 0.005,
    },
    {
      default: 3,
      key: "alphaGain",
      label: "Alpha gain",
      max: 15,
      min: 0.05,
      step: 0.1,
    },
    {
      default: 0.45,
      key: "edgeFade",
      label: "Halo falloff",
      max: 3,
      min: 0.1,
      step: 0.015,
    },
    {
      default: 12,
      key: "camDist",
      label: "Camera distance",
      max: 100,
      min: 1.5,
      step: 0.5,
    },
    { default: 3.5, key: "fov", label: "Lens", max: 20, min: 0.3, step: 0.1 },
    {
      default: 9,
      key: "stepScale",
      label: "Step safety",
      max: 30,
      min: 0.3,
      step: 0.5,
    },
    {
      default: 22,
      key: "maxDist",
      label: "Max distance",
      max: 100,
      min: 3,
      step: 1,
    },
  ],
  shader: orb31Shader,
  statePresets: {
    idle: {
      alphaGain: 3,
      freqSwing: 0,
      rayFalloff: 10.5,
      rayGain: 0.8,
      smoothK: 0.42,
      smoothSwing: 0,
      speed: 1,
      swell: 0.18,
      warp: 0.9,
      warpFreq: 5.25,
      warpSwing: 0,
    },
    speaking: {
      alphaGain: 1.8,
      freqSwing: 4.5,
      rayFalloff: 8,
      rayGain: 0.52,
      smoothK: 0.25,
      smoothSwing: 0.25,
      speed: 0.9,
      sweepRate: 0.8,
      swell: 0.66,
      warp: 3.75,
      warpFreq: 19.5,
      warpSwing: 2.25,
    },
    thinking: {
      alphaGain: 1.8,
      freqSwing: 2,
      rayFalloff: 8,
      rayGain: 0.52,
      smoothK: 0.58,
      smoothSwing: 0,
      speed: 0.9,
      sweepRate: 0.5,
      swell: 0.66,
      warp: 1,
      warpFreq: 7,
      warpSwing: 0,
    },
  },
};
