import type { OrbVariant } from "@/components/orbs/canvas";
import { orb10Shader } from "@/components/orbs/orb-10/gpu";

export const meta = {
  description: "a lattice of light knitted into the ball's own skin",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-10",
  title: "ORB-10",
} as const;

export const orb10Orb: OrbVariant = {
  colors: [{ default: "#ffffff", key: "tint", label: "Tint" }],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.6,
      integrate: true,
      key: "speed",
      label: "Anim speed",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 1.2,
      integrate: true,
      key: "scroll",
      label: "Climb",
      max: 8,
      min: 0,
      step: 0.03,
    },
    {
      default: 7,
      key: "camDist",
      label: "Camera distance",
      max: 50,
      min: 1,
      step: 0.3,
    },
    { default: 2, key: "focal", label: "Lens", max: 15, min: 0.15, step: 0.05 },
    {
      default: 2.6,
      key: "shellR",
      label: "Shell radius",
      max: 20,
      min: 0.2,
      step: 0.1,
    },
    {
      default: 8,
      key: "wrap",
      label: "Wraps around",
      max: 14,
      min: 1,
      step: 1,
    },
    {
      default: 4,
      key: "climb",
      label: "Band spacing",
      max: 12,
      min: 0.05,
      step: 0.05,
    },
    { default: 0.35, key: "turb", label: "Warp", max: 3, min: 0, step: 0.02 },
    {
      default: 0.5,
      key: "layer",
      label: "Layer offset",
      max: 2,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.45,
      key: "cell",
      label: "Lattice weight",
      max: 2,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.15,
      key: "stepScale",
      label: "Step scale",
      max: 3,
      min: 0.02,
      step: 0.005,
    },
    {
      default: 0.4,
      key: "hueStep",
      label: "Layer hue",
      max: 3,
      min: 0,
      step: 0.01,
    },
    {
      default: 1,
      key: "spread",
      label: "Colour spread",
      max: 3,
      min: 0,
      step: 0.02,
    },
    {
      default: 2.9,
      key: "envRadius",
      label: "Envelope radius",
      max: 20,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 0.92,
      key: "envCore",
      label: "Envelope core",
      max: 1.02,
      min: 0.3,
      step: 0.01,
    },
    {
      default: 0.1,
      key: "fill",
      label: "Body fill",
      max: 40,
      min: 0,
      step: 0.05,
    },
    {
      default: 300,
      key: "stepClamp",
      label: "Step clamp",
      max: 5000,
      min: 5,
      step: 5,
    },
    {
      default: 0.004,
      key: "scatter",
      label: "Diffusion",
      max: 0.2,
      min: 0,
      step: 0.0005,
    },
    {
      default: 30,
      key: "exposure",
      label: "Exposure",
      max: 500,
      min: 0.05,
      step: 0.5,
    },
    {
      default: 1.15,
      key: "contrast",
      label: "Contrast",
      max: 15,
      min: 0.15,
      step: 0.05,
    },
    {
      default: 1.2,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 2,
      key: "alphaGain",
      label: "Alpha gain",
      max: 15,
      min: 0.05,
      step: 0.1,
    },
    {
      default: 1,
      key: "edge",
      label: "Edge sharpness",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.98,
      key: "edgeFade",
      label: "Halo falloff",
      max: 3,
      min: 0.1,
      step: 0.015,
    },
  ],
  shader: orb10Shader,
  stateColors: {
    idle: { tint: "#ffffff" },
    speaking: { tint: "#ffc492" },
    thinking: { tint: "#e8f4ff" },
  },

  statePresets: {
    idle: {
      alphaGain: 2,
      cell: 0.45,
      exposure: 30,
      scatter: 0.004,
      scroll: 1.2,
      speed: 0.6,
      turb: 0.35,
    },
    speaking: {
      alphaGain: 2.8,
      cell: 0.95,
      contrast: 0.9,
      exposure: 11,
      saturation: 1.45,
      scatter: 0.0015,
      scroll: 4.2,
      speed: 1,
      turb: 0.18,
    },
    thinking: {
      alphaGain: 2.6,
      cell: 0.3,
      contrast: 1.05,
      exposure: 13,
      fill: 0.12,
      layer: 0.65,
      saturation: 1.7,
      scatter: 0.006,
      scroll: 0.5,
      speed: 1.9,
      spread: 1.55,
      stepScale: 0.09,
      turb: 0.85,
    },
  },
};
