import type { OrbVariant } from "@/components/orbs/canvas";
import { orb15Params, orb15Shader } from "@/components/orbs/orb-15/gpu";

export const meta = {
  description: "an iridescent particle-track web worn as the ball's skin",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-15",
  title: "ORB-15",
} as const;

export const orb15Orb: OrbVariant = {
  colors: [{ default: "#ffffff", key: "tint", label: "Tint" }],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.5,
      integrate: true,
      key: "speed",
      label: "Anim speed",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0.15,
      integrate: true,
      key: "wander",
      label: "Axis wander",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 7,
      key: "camDist",
      label: "Camera distance",
      max: 50,
      min: 1,
      step: 0.3,
    },
    {
      default: 2.25,
      key: "focal",
      label: "Lens",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 2.4,
      key: "fieldScale",
      label: "Web density",
      max: 20,
      min: 1,
      step: 0.1,
    },
    { default: 0.8, key: "turb", label: "Weave", max: 5, min: 0, step: 0.03 },
    {
      default: 0.015,
      key: "stepScale",
      label: "Skin depth",
      max: 0.4,
      min: 0.0015,
      step: 0.005,
    },
    {
      default: 1,
      key: "disperse",
      label: "Dispersion",
      max: 5,
      min: 0,
      step: 0.03,
    },
    {
      default: 2.6,
      key: "envRadius",
      label: "Envelope radius",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 1,
      key: "envCore",
      label: "Envelope core",
      max: 1.02,
      min: 0.3,
      step: 0.01,
    },
    {
      default: 0.3,
      key: "fill",
      label: "Body fill",
      max: 100,
      min: 0,
      step: 0.3,
    },
    {
      default: 150,
      key: "stepClamp",
      label: "Step clamp",
      max: 5000,
      min: 3,
      step: 30,
    },
    {
      default: 0.01,
      key: "scatter",
      label: "Diffusion",
      max: 0.5,
      min: 0,
      step: 0.003,
    },
    {
      default: 50,
      key: "exposure",
      label: "Exposure",
      max: 1500,
      min: 1.5,
      step: 10,
    },
    {
      default: 1.35,
      key: "contrast",
      label: "Contrast",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 1.35,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 2,
      key: "alphaGain",
      label: "Alpha gain",
      max: 15,
      min: 0.05,
      step: 0.1,
    },
    {
      default: 1,
      key: "edge",
      label: "Edge sharpness",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.98,
      key: "edgeFade",
      label: "Halo falloff",
      max: 3,
      min: 0.1,
      step: 0.015,
    },
  ],
  /*
    Staged on the two integrated clocks, as across the family: thinking
    sends the AXIS hunting (the web continuously reweaves in place) while
    speaking is speed-led (the layer-cycled iridescence shimmers fast and
    bright). turb and disperse are amplitudes/phases — everything glides.
  */
  shader: orb15Shader,
  statePresets: {
    idle: {
      alphaGain: 2,
      disperse: 1,
      exposure: 72,
      scatter: 0.01,
      speed: 0.4,
      turb: 0.75,
      wander: 0.12,
    },
    speaking: {
      alphaGain: 2.5,
      disperse: 1.6,
      exposure: 46,
      scatter: 0.0075,
      speed: 2,
      turb: 1.1,
      wander: 0.3,
    },
    thinking: {
      alphaGain: 2.1,
      disperse: 0.8,
      exposure: 66,
      scatter: 0.0095,
      speed: 1,
      turb: 0.95,
      wander: 0.7,
    },
  },
  uniforms: orb15Params,
};
