import { orb11Shader } from "@/components/orbs/orb-11/gpu";
import type { OrbVariant } from "@/components/orbs/orbkit-core-wgpu";

export const meta = {
  description: "quantum orbital, rainbow chroma",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-11",
  title: "ORB-11",
} as const;

export const orb11Orb: OrbVariant = {
  colors: [],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.9,
      integrate: true,
      key: "speed",
      label: "Anim speed",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0.5,
      key: "rotSpeed",
      label: "Rotation speed",
      max: 5,
      min: 0,
      step: 0.05,
    },
    {
      default: 0.9,
      key: "radius",
      label: "Radius",
      max: 3,
      min: 0.15,
      step: 0.015,
    },
    {
      default: 0.07,
      key: "swell",
      label: "Input swell",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.5,
      key: "posScale",
      label: "Orbital zoom",
      max: 10,
      min: 0.15,
      step: 0.05,
    },
    {
      default: 0.35,
      integrate: true,
      key: "flowSpeed",
      label: "Flow speed",
      max: 10,
      min: 0,
      step: 0.05,
    },
    {
      default: 0.45,
      key: "flowAmp",
      label: "Flow amount",
      max: 4,
      min: 0,
      step: 0.05,
    },
    {
      default: 0.3,
      key: "flowScale",
      label: "Flow scale",
      max: 10,
      min: 0.3,
      step: 0.1,
    },
    {
      default: 0.3,
      key: "precess",
      label: "Precession",
      max: 4,
      min: 0,
      step: 0.05,
    },
    {
      default: 0.5,
      key: "radialPow",
      label: "Radial power",
      max: 15,
      min: 0.5,
      step: 0.1,
    },
    {
      default: 1,
      key: "radialDecay",
      label: "Radial decay",
      max: 30,
      min: 0.3,
      step: 0.15,
    },
    {
      default: 0.4,
      key: "probPow",
      label: "Probability curve",
      max: 3,
      min: 0.1,
      step: 0.015,
    },
    {
      default: 3,
      key: "probGain",
      label: "Probability gain",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 4,
      key: "waveFreq",
      label: "Wave frequency",
      max: 20,
      min: 0,
      step: 0.5,
    },
    {
      default: 0.18,
      key: "chromaSpread",
      label: "Chroma spread",
      max: 1.5,
      min: 0,
      step: 0.01,
    },
    { default: 0.9, key: "glow", label: "Glow", max: 5, min: 0, step: 0.05 },
    {
      default: 0,
      key: "metalDark",
      label: "Metal darkness",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0.12,
      key: "baseVis",
      label: "Base visibility",
      max: 1.5,
      min: 0,
      step: 0.01,
    },
  ],
  shader: orb11Shader,
  statePresets: {
    idle: {
      baseVis: 0.12,
      chromaSpread: 0.18,
      flowAmp: 0.45,
      flowScale: 0.3,
      flowSpeed: 0.35,
      glow: 0.9,
      metalDark: 0,
      posScale: 0.5,
      precess: 0.3,
      probGain: 3,
      probPow: 0.4,
      radialDecay: 1,
      radialPow: 0.5,
      radius: 0.9,
      rotSpeed: 0.5,
      speed: 0.9,
      swell: 0.07,
      waveFreq: 4,
    },
    speaking: {
      baseVis: 0.12,
      chromaSpread: 0.12,
      flowAmp: 0.8,
      flowScale: 2.2,
      flowSpeed: 2.75,
      glow: 0.9,
      metalDark: 0,
      posScale: 1,
      precess: 1.3,
      probGain: 4.3,
      probPow: 0.31,
      radialDecay: 1,
      radialPow: 0.5,
      radius: 0.9,
      rotSpeed: 0.5,
      speed: 2.45,
      swell: 0.07,
      waveFreq: 4,
    },
    thinking: {
      baseVis: 0.12,
      chromaSpread: 0.41,
      flowAmp: 1.1,
      flowScale: 0.3,
      flowSpeed: 0.35,
      glow: 0.9,
      metalDark: 0,
      posScale: 0.65,
      precess: 0,
      probGain: 3,
      probPow: 0.4,
      radialDecay: 1.9,
      radialPow: 0.5,
      radius: 0.9,
      rotSpeed: 0.5,
      speed: 0.9,
      swell: 0.07,
      waveFreq: 4,
    },
  },
};
