import type { OrbVariant } from "@/components/orbs/canvas";
import { orb25Shader } from "@/components/orbs/orb-25/gpu";

export const meta = {
  description: "the folds of a warped field, drawn by their own steepness",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-25",
  title: "ORB-25",
} as const;

export const orb25Orb: OrbVariant = {
  colors: [
    { default: "#dbe8f7", key: "tint", label: "Rim" },
    { default: "#0d1118", key: "body", label: "Body" },
    { default: "#a8c8f0", key: "sheen", label: "Sheen" },
  ],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 3,
      integrate: true,
      key: "speed",
      label: "Boil",
      max: 20,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0.6,
      integrate: true,
      key: "drift",
      label: "Drift",
      max: 8,
      min: 0,
      step: 0.02,
    },
    {
      default: 0.05,
      integrate: true,
      key: "swirl",
      label: "Swirl",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0.9,
      key: "radius",
      label: "Radius",
      max: 3,
      min: 0.15,
      step: 0.015,
    },
    {
      default: 7.5,
      key: "scale",
      label: "Cell scale",
      max: 60,
      min: 0.3,
      step: 0.1,
    },
    {
      default: 0.3,
      key: "bulge",
      label: "Dome bulge",
      max: 4,
      min: 0,
      step: 0.02,
    },
    { default: 0.4, key: "warp", label: "Fold", max: 2, min: 0, step: 0.01 },
    {
      default: 1.111,
      key: "zoom",
      label: "Octave zoom",
      max: 2,
      min: 0.6,
      step: 0.005,
    },
    {
      default: 0.3,
      key: "ripple",
      label: "Ripple",
      max: 3,
      min: 0.02,
      step: 0.01,
    },
    {
      default: 10,
      key: "edgeGain",
      label: "Edge gain",
      max: 60,
      min: 0.5,
      step: 0.5,
    },
    {
      default: 2.5,
      key: "blur",
      label: "Rim width",
      max: 12,
      min: 0.5,
      step: 0.25,
    },
    {
      default: 0.09,
      key: "fringe",
      label: "Chromatic fringe",
      max: 1.5,
      min: 0,
      step: 0.005,
    },
    {
      default: 0.8,
      key: "exposure",
      label: "Exposure",
      max: 40,
      min: 0.05,
      step: 0.05,
    },
    {
      default: 1.15,
      key: "contrast",
      label: "Contrast",
      max: 8,
      min: 0.15,
      step: 0.05,
    },
    {
      default: 1.5,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 0.16,
      key: "floorLevel",
      label: "Body fill",
      max: 2,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.35,
      key: "light",
      label: "Key light",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0.45,
      key: "rim",
      label: "Rim sheen",
      max: 3,
      min: 0,
      step: 0.015,
    },
  ],
  // cool steel at rest, cold indigo for both working states — the answer
  // is told apart by its fold and scale, not its colour
  shader: orb25Shader,
  stateColors: {
    idle: { body: "#0d1118", sheen: "#a8c8f0", tint: "#dbe8f7" },
    speaking: { body: "#090d1c", sheen: "#8fb4f2", tint: "#c2d6f5" },
    thinking: { body: "#090d1c", sheen: "#8fb4f2", tint: "#c2d6f5" },
  },
  /*
    Staged on the FOLD, which is what makes creases exist at all, and on
    edge gain, which decides how steep a slope has to be to count as one.
    Cell scale moves only for the answer — it sets how much pattern is on
    the ball, and as it glides in the ball reads as inflating; that is the
    answer's entrance.
  */
  statePresets: {
    idle: {
      contrast: 1.15,
      drift: 0.6,
      edgeGain: 12.5,
      exposure: 0.8,
      speed: 3,
      swirl: 0.05,
      warp: 0.4,
      zoom: 1.07,
    },
    speaking: {
      blur: 2,
      bulge: 2.22,
      contrast: 1.35,
      drift: 0.8,
      edgeGain: 5,
      exposure: 2.35,
      fringe: 0.23,
      ripple: 1.18,
      scale: 11.5,
      speed: 1.4,
      swirl: 0.6,
      warp: 1.55,
      zoom: 0.945,
    },
    thinking: {
      blur: 2.75,
      bulge: 0.38,
      contrast: 1.5,
      drift: 0.15,
      edgeGain: 33,
      exposure: 0.55,
      fringe: 0.2,
      light: 0.525,
      rim: 0.69,
      ripple: 0.18,
      saturation: 2,
      speed: 4.7,
      swirl: 0.02,
      warp: 0.34,
      zoom: 1.12,
    },
  },
};
