import type { OrbVariant } from "@/components/orbs/canvas";
import { orb30Params, orb30Shader } from "@/components/orbs/orb-30/gpu";

export const meta = {
  description: "a meadow folding into itself toward a blue vanishing point",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-30",
  title: "ORB-30",
} as const;

export const orb30Orb: OrbVariant = {
  /*
   * Six stops, and they are the picture rather than a palette: the sky the
   * recursion closes on, its cloud, the dark canopy, the meadow under the
   * flowers, the planted warm colour, and the glass.
   */
  colors: [
    { default: "#4a92e0", key: "sky", label: "Sky" },
    { default: "#f7fbff", key: "cloud", label: "Cloud" },
    { default: "#12401f", key: "canopy", label: "Canopy" },
    { default: "#5aa63a", key: "meadow", label: "Meadow" },
    { default: "#156f6a", key: "water", label: "Water" },
    { default: "#ff6a3a", key: "bloom", label: "Bloom" },
    { default: "#cfe6ff", key: "sheen", label: "Sheen" },
  ],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.12,
      integrate: true,
      key: "fall",
      label: "Fall speed",
      max: 4,
      min: 0,
      step: 0.01,
    },
    {
      default: 0,
      key: "tilt",
      label: "Frame tilt",
      max: 1.6,
      min: -1.6,
      step: 0.01,
    },
    {
      default: 0.2,
      integrate: true,
      key: "drift",
      label: "Weather drift",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 0.9,
      key: "radius",
      label: "Radius",
      max: 3,
      min: 0.15,
      step: 0.015,
    },
    {
      default: 4.5,
      key: "scale",
      label: "Tunnel scale",
      max: 20,
      min: 0.3,
      step: 0.1,
    },
    {
      default: 0.25,
      key: "bulge",
      label: "Dome bulge",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 1.8,
      key: "ratio",
      label: "Frame ratio",
      max: 6,
      min: 1.1,
      step: 0.02,
    },
    {
      default: 0.14,
      key: "horizon",
      label: "Horizon",
      max: 0.9,
      min: -0.9,
      step: 0.01,
    },
    {
      default: 1.6,
      key: "cloudScale",
      label: "Cloud scale",
      max: 8,
      min: 0.1,
      step: 0.05,
    },
    {
      default: 0.46,
      key: "cloudCover",
      label: "Cloud cover",
      max: 0.98,
      min: 0.02,
      step: 0.01,
    },
    {
      default: 5,
      key: "streakFreq",
      label: "Wall detail",
      max: 20,
      min: 0.2,
      step: 0.1,
    },
    {
      default: 0.5,
      key: "streakRad",
      label: "Smear",
      max: 4,
      min: 0.02,
      step: 0.02,
    },
    { default: 0.7, key: "water", label: "Water", max: 1, min: 0, step: 0.01 },
    {
      default: 44,
      key: "flowerScale",
      label: "Flower scale",
      max: 120,
      min: 2,
      step: 1,
    },
    {
      default: 0.55,
      key: "flowerDensity",
      label: "Flower density",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.26,
      key: "flowerSize",
      label: "Flower size",
      max: 0.6,
      min: 0.05,
      step: 0.01,
    },
    {
      default: 0.62,
      key: "frameShade",
      label: "Frame shading",
      max: 1.4,
      min: 0.2,
      step: 0.01,
    },
    {
      default: 0.85,
      key: "haze",
      label: "Aerial haze",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.09,
      key: "hazeRange",
      label: "Haze reach",
      max: 1.5,
      min: 0.005,
      step: 0.005,
    },
    {
      default: 1.05,
      key: "gain",
      label: "Brightness",
      max: 4,
      min: 0.05,
      step: 0.02,
    },
    {
      default: 1.05,
      key: "contrast",
      label: "Contrast",
      max: 10,
      min: 0.15,
      step: 0.05,
    },
    {
      default: 1.1,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 0.35,
      key: "light",
      label: "Key light",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0.55,
      key: "rim",
      label: "Rim sheen",
      max: 3,
      min: 0,
      step: 0.015,
    },
  ],
  // the picture keeps its own colours; the states move the weather and the
  // light, cooling toward overcast while searching and warming while
  // answering
  shader: orb30Shader,
  stateColors: {
    idle: {
      bloom: "#ff6a3a",
      canopy: "#12401f",
      cloud: "#f7fbff",
      meadow: "#5aa63a",
      sheen: "#cfe6ff",
      sky: "#4a92e0",
      water: "#156f6a",
    },
    speaking: {
      bloom: "#ffb02e",
      canopy: "#204a16",
      cloud: "#fff6e8",
      meadow: "#7cc23f",
      sheen: "#ffe3c4",
      sky: "#6fb0ec",
      water: "#1d8a76",
    },
    thinking: {
      bloom: "#7d8cff",
      canopy: "#0e2c2e",
      cloud: "#dde8f4",
      meadow: "#3f7f5c",
      sheen: "#b6cdf0",
      sky: "#3f6fa8",
      water: "#12525f",
    },
  },
  /*
    Staged on the fall, which is the orb's whole subject, and on the haze,
    which decides how far into the recursion the eye can see. Frame ratio
    sets how many frames land on the ball; it differs only for idle, and
    the glide out of rest reads as the tunnel breathing once.
  */
  statePresets: {
    idle: {
      bulge: 0.2,
      cloudCover: 0.42,
      cloudScale: 1.2,
      drift: 0.2,
      fall: 0.12,
      flowerDensity: 0.27,
      flowerScale: 24,
      flowerSize: 0.43,
      gain: 1.38,
      haze: 0.8,
      hazeRange: 0.09,
      horizon: -0.11,
      light: 0.345,
      ratio: 3.06,
      rim: 0.555,
      saturation: 1.56,
      streakFreq: 2.9,
      streakRad: 0.54,
      water: 0,
    },
    speaking: {
      cloudCover: 0.44,
      cloudScale: 3.65,
      contrast: 1.45,
      drift: 1.54,
      fall: 1.47,
      flowerDensity: 0.95,
      flowerScale: 32,
      gain: 1.36,
      haze: 0.38,
      hazeRange: 0.315,
      horizon: 0.03,
      light: 0.57,
      saturation: 2.32,
      scale: 8.7,
      streakFreq: 11,
      streakRad: 1.48,
      tilt: 0.03,
    },
    thinking: {
      cloudCover: 0.3,
      contrast: 1.45,
      drift: 0.5,
      fall: 0.6,
      flowerDensity: 0.28,
      gain: 1.42,
      haze: 1,
      hazeRange: 0.3,
      light: 0.96,
      saturation: 2,
    },
  },
  uniforms: orb30Params,
};
