import { orb27Shader } from "@/components/orbs/orb-27/gpu";
import type { OrbVariant } from "@/components/orbs/orbkit-core-wgpu";

export const meta = {
  description:
    "a weather-radar mosaic, fronts of coloured pixels sweeping the ball",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-27",
  title: "ORB-27",
} as const;

export const orb27Orb: OrbVariant = {
  /*
   * The paper and the seven classes, quiet to peak: grey, blue, cyan,
   * green, red, yellow, magenta — the radar legend of the reference.
   */
  colors: [
    { default: "#efe9dc", key: "paper", label: "Paper" },
    { default: "#a9a9a6", key: "c0", label: "Quiet" },
    { default: "#2e5df0", key: "c1", label: "Class 1" },
    { default: "#38d9ec", key: "c2", label: "Class 2" },
    { default: "#22c35c", key: "c3", label: "Class 3" },
    { default: "#e8322a", key: "c4", label: "Class 4" },
    { default: "#f5d020", key: "c5", label: "Class 5" },
    { default: "#e030c0", key: "c6", label: "Peak" },
  ],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.6,
      integrate: true,
      key: "speed",
      label: "Front speed",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0.04,
      integrate: true,
      key: "spin",
      label: "Roll",
      max: 5,
      min: 0,
      step: 0.03,
    },
    {
      default: 0.9,
      key: "radius",
      label: "Radius",
      max: 3,
      min: 0.15,
      step: 0.015,
    },
    {
      default: 2.4,
      key: "scale",
      label: "Grid zoom",
      max: 8,
      min: 0.3,
      step: 0.05,
    },
    { default: 34, key: "cells", label: "Grid", max: 120, min: 8, step: 1 },
    {
      default: 0.36,
      key: "dot",
      label: "Dot size",
      max: 0.5,
      min: 0.1,
      step: 0.01,
    },
    { default: 1.5, key: "swirl", label: "Swirl", max: 8, min: 0, step: 0.05 },
    {
      default: 0.45,
      key: "vortex",
      label: "Vortex size",
      max: 2,
      min: 0.1,
      step: 0.01,
    },
    {
      default: 1.6,
      key: "freq",
      label: "Storm scale",
      max: 8,
      min: 0.2,
      step: 0.05,
    },
    { default: 0.5, key: "warp", label: "Bend", max: 3, min: 0, step: 0.02 },
    {
      default: 0.12,
      key: "lo",
      label: "Quiet threshold",
      max: 1,
      min: 0,
      step: 0.005,
    },
    {
      default: 0.82,
      key: "hi",
      label: "Peak threshold",
      max: 1,
      min: 0,
      step: 0.005,
    },
    {
      default: 1.4,
      key: "curve",
      label: "Response curve",
      max: 4,
      min: 0.5,
      step: 0.05,
    },
    {
      default: 0.12,
      key: "dither",
      label: "Class dither",
      max: 0.6,
      min: 0,
      step: 0.005,
    },
    {
      default: 0.16,
      key: "sparse",
      label: "Quiet density",
      max: 1,
      min: 0,
      step: 0.01,
    },
    { default: 1, key: "density", label: "Fill", max: 1.5, min: 0, step: 0.01 },
    {
      default: 3,
      key: "twinkle",
      label: "Twinkle rate",
      max: 30,
      min: 0,
      step: 0.5,
    },
    {
      default: 0.1,
      key: "grain",
      label: "Paper grain",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.18,
      key: "light",
      label: "Key light",
      max: 1,
      min: 0,
      step: 0.01,
    },
    { default: 0.35, key: "rim", label: "Rim", max: 1, min: 0, step: 0.01 },
  ],
  // the legend holds; the paper cools while searching and warms while
  // answering
  shader: orb27Shader,
  stateColors: {
    idle: { paper: "#efe9dc" },
    speaking: { paper: "#f5e6d0" },
    thinking: { paper: "#e6e9ee" },
  },
  /*
    Staged on the drift, the swirl, the window and the fill. The grid, the
    zoom and the storm scale all multiply a coordinate or sit inside a
    floor, so they never move between states. The swirl is an angle,
    bounded, and glides safely.
  */
  statePresets: {
    idle: {
      curve: 1.4,
      density: 1,
      dither: 0.12,
      hi: 0.82,
      lo: 0.12,
      sparse: 0.16,
      speed: 1,
      spin: 0.27,
      swirl: 1.5,
      twinkle: 3,
      warp: 0.5,
    },
    speaking: {
      curve: 1.3,
      density: 1.15,
      dither: 0.1,
      grain: 0.35,
      hi: 0.8,
      lo: 0,
      sparse: 0.22,
      speed: 6.5,
      spin: 0.51,
      swirl: 2,
      twinkle: 5,
      warp: 0.45,
    },
    thinking: {
      curve: 1.7,
      density: 0.9,
      dither: 0.18,
      freq: 5.2,
      hi: 0.545,
      lo: 0,
      sparse: 0.22,
      speed: 2.4,
      spin: 0.51,
      swirl: 4,
      twinkle: 12,
      warp: 1.06,
    },
  },
};
