import type { OrbVariant } from "@/components/orbs/canvas";
import { orb23Shader } from "@/components/orbs/orb-23/gpu";

export const meta = {
  description: "an ASCII glyph matrix in CRT green, wrapped on the ball",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-23",
  title: "ORB-23",
} as const;

export const orb23Orb: OrbVariant = {
  colors: [
    { default: "#57ffc9", key: "glow", label: "Glow" },
    { default: "#0b3b2d", key: "deep", label: "Deep" },
  ],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.55,
      integrate: true,
      key: "drift",
      label: "Drift",
      max: 10,
      min: 0,
      step: 0.05,
    },
    {
      default: 0.05,
      integrate: true,
      key: "scroll",
      label: "Scroll",
      max: 10,
      min: 0,
      step: 0.05,
    },
    {
      default: 0.5,
      integrate: true,
      key: "speed",
      label: "Pulse rate",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0,
      key: "pulse",
      label: "Pulse depth",
      max: 2,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.12,
      integrate: true,
      key: "spin",
      label: "Roll",
      max: 5,
      min: 0,
      step: 0.03,
    },
    {
      default: 0.9,
      key: "radius",
      label: "Radius",
      max: 3,
      min: 0.15,
      step: 0.015,
    },
    {
      default: 40,
      key: "cells",
      label: "Glyph grid",
      max: 120,
      min: 16,
      step: 2,
    },
    {
      default: 1.6,
      key: "scale",
      label: "Field scale",
      max: 10,
      min: 0.3,
      step: 0.1,
    },
    {
      default: 0.48,
      key: "density",
      label: "Glyph density",
      max: 2,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.48,
      key: "dropout",
      label: "Dropout",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.6,
      key: "light",
      label: "Key light",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 0.45,
      key: "rim",
      label: "Rim glow",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 1,
      key: "gain",
      label: "Phosphor gain",
      max: 5,
      min: 0.05,
      step: 0.05,
    },
    {
      default: 1,
      key: "contrast",
      label: "Contrast",
      max: 10,
      min: 0.15,
      step: 0.05,
    },
  ],
  // violet at rest, aqua while searching, red while answering
  shader: orb23Shader,
  stateColors: {
    idle: { glow: "#6a57ff" },
    speaking: { glow: "#ff5757" },
    thinking: { glow: "#57ffe3" },
  },
  /*
    Each state ANIMATES differently — its own kind of motion, not just its
    own speed — and each has its own phosphor colour. Every motion has its own integrated clock, so a rate gliding to zero
    freezes that motion in place with its phase intact; the pulse depth is
    an amplitude.
  */
  statePresets: {
    idle: {
      cells: 68,
      density: 0.31,
      drift: 0.55,
      dropout: 0.24,
      gain: 0.9,
      light: 1.11,
      pulse: 0,
      rim: 0.66,
      scale: 5.1,
      scroll: 0.05,
      speed: 0.52,
      spin: 0.12,
    },
    speaking: {
      cells: 120,
      density: 0.56,
      drift: 0.4,
      dropout: 0.59,
      gain: 2.95,
      light: 0.39,
      pulse: 1.27,
      rim: 0.51,
      scale: 7.2,
      scroll: 0.1,
      speed: 2.85,
      spin: 1.05,
    },
    thinking: {
      cells: 86,
      contrast: 1.3,
      density: 0.33,
      drift: 3.05,
      dropout: 0.13,
      gain: 0.95,
      light: 0.855,
      pulse: 0.58,
      rim: 0.51,
      scroll: 0.65,
      speed: 0.45,
      spin: 0.04,
    },
  },
};
