import type { OrbVariant } from "@/components/orbs/canvas";
import { orb13Shader } from "@/components/orbs/orb-13/gpu";

export const meta = {
  description: "plasma globe: crawling lightning filaments",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-13",
  title: "ORB-13",
} as const;

export const orb13Orb: OrbVariant = {
  colors: [
    { default: "#ff70d8", key: "inner", label: "Nucleus" },
    { default: "#5a5cff", key: "arc", label: "Arc" },
    { default: "#ffffff", key: "tint", label: "Tint" },
  ],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 1,
      integrate: true,
      key: "speed",
      label: "Anim speed",
      max: 10,
      min: 0.015,
      step: 0.05,
    },
    {
      default: 0.2,
      integrate: true,
      key: "spin",
      label: "Spin rate",
      max: 5,
      min: 0,
      step: 0.03,
    },
    {
      default: 7,
      key: "camDist",
      label: "Camera distance",
      max: 50,
      min: 1,
      step: 0.3,
    },
    {
      default: 2.25,
      key: "focal",
      label: "Lens",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 2.6,
      key: "envRadius",
      label: "Globe radius",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 0.15,
      key: "swell",
      label: "Input swell",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.4,
      key: "tilt",
      label: "Axis tilt",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 6,
      key: "fils",
      label: "Filament density",
      max: 12,
      min: 0.5,
      step: 0.1,
    },
    {
      default: 0.9,
      key: "writhe",
      label: "Writhe",
      max: 3,
      min: 0,
      step: 0.02,
    },
    {
      default: 1.6,
      key: "writheFreq",
      label: "Writhe frequency",
      max: 8,
      min: 0.2,
      step: 0.05,
    },
    {
      default: 4,
      key: "sharp",
      label: "Arc sharpness",
      max: 60,
      min: 0.5,
      step: 0.5,
    },
    {
      default: 0.06,
      key: "soft",
      label: "Arc core softness",
      max: 0.5,
      min: 0.002,
      step: 0.002,
    },
    {
      default: 0.008,
      key: "whiten",
      label: "Core whitening",
      max: 0.2,
      min: 0,
      step: 0.002,
    },
    {
      default: 1.6,
      key: "coreGain",
      label: "Nucleus glow",
      max: 5,
      min: 0,
      step: 0.05,
    },
    {
      default: 1.8,
      key: "tipGain",
      label: "Glass flare",
      max: 6,
      min: 0,
      step: 0.05,
    },
    {
      default: 0.02,
      key: "fill",
      label: "Body haze",
      max: 2,
      min: 0,
      step: 0.01,
    },
    {
      default: 40,
      key: "stepClamp",
      label: "Step clamp",
      max: 300,
      min: 0.3,
      step: 1.5,
    },
    {
      default: 0.012,
      key: "scatter",
      label: "Diffusion",
      max: 0.5,
      min: 0,
      step: 0.003,
    },
    {
      default: 11,
      key: "exposure",
      label: "Exposure",
      max: 200,
      min: 0.1,
      step: 0.5,
    },
    {
      default: 1,
      key: "contrast",
      label: "Contrast",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 1.2,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 2.5,
      key: "alphaGain",
      label: "Alpha gain",
      max: 15,
      min: 0.05,
      step: 0.1,
    },
    {
      default: 1,
      key: "edge",
      label: "Edge sharpness",
      max: 1,
      min: 0,
      step: 0.01,
    },
  ],
  shader: orb13Shader,
  statePresets: {
    idle: {
      coreGain: 1.6,
      exposure: 11,
      fils: 6,
      sharp: 4,
      soft: 0.06,
      speed: 1,
      spin: 0.2,
      tipGain: 1.8,
      whiten: 0.008,
      writhe: 0.9,
    },
    speaking: {
      coreGain: 2,
      exposure: 8.5,
      fils: 8,
      sharp: 3.5,
      soft: 0.05,
      speed: 2.6,
      spin: 0.3,
      tipGain: 2.4,
      whiten: 0.012,
      writhe: 1.3,
    },
    thinking: {
      coreGain: 1.2,
      exposure: 10,
      fils: 7,
      sharp: 3,
      soft: 0.08,
      speed: 1.8,
      spin: 0.45,
      tipGain: 1.5,
      whiten: 0.012,
      writhe: 1.2,
    },
  },
};
