import type { OrbVariant } from "@/components/orbs/canvas";
import { orb32Params, orb32Shader } from "@/components/orbs/orb-32/gpu";

export const meta = {
  description: "a galaxy marched as gas and dust inside the ball",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-32",
  title: "ORB-32",
} as const;

export const orb32Orb: OrbVariant = {
  /*
   * Six stops: the overall tint, the core the bulge whitens toward, the
   * inner and outer arm colours the ramp runs between, the night the ball
   * is filled with, and the glass rim.
   */
  colors: [
    { default: "#ffffff", key: "tint", label: "Tint" },
    { default: "#fff3d6", key: "core", label: "Core" },
    { default: "#7fb4ff", key: "inner", label: "Inner arms" },
    { default: "#c46bff", key: "outer", label: "Outer arms" },
    { default: "#04050f", key: "deep", label: "Night" },
    { default: "#8fb0ff", key: "rim", label: "Rim" },
  ],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.06,
      integrate: true,
      key: "spin",
      label: "Disc turn",
      max: 3,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.25,
      integrate: true,
      key: "churn",
      label: "Gas churn",
      max: 5,
      min: 0,
      step: 0.02,
    },
    {
      default: 0.8,
      integrate: true,
      key: "beat",
      label: "Core beat",
      max: 12,
      min: 0,
      step: 0.05,
    },
    {
      default: 1.2,
      integrate: true,
      key: "twinkle",
      label: "Twinkle rate",
      max: 12,
      min: 0,
      step: 0.05,
    },
    {
      default: 7,
      key: "camDist",
      label: "Camera distance",
      max: 50,
      min: 1,
      step: 0.3,
    },
    {
      default: 2.25,
      key: "focal",
      label: "Lens",
      max: 15,
      min: 0.15,
      step: 0.05,
    },
    {
      default: 2.6,
      key: "envRadius",
      label: "Envelope radius",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 0.85,
      key: "tilt",
      label: "Tilt (0 edge-on)",
      max: 1.5,
      min: 0,
      step: 0.01,
    },
    { default: 2, key: "arms", label: "Arm count", max: 6, min: 1, step: 1 },
    {
      default: 3.4,
      key: "wind",
      label: "Arm winding",
      max: 8,
      min: 0,
      step: 0.05,
    },
    {
      default: 3,
      key: "ragged",
      label: "Arm fray",
      max: 12,
      min: 0,
      step: 0.05,
    },
    {
      default: 2.2,
      key: "armSharp",
      label: "Arm sharpness",
      max: 8,
      min: 0.3,
      step: 0.05,
    },
    {
      default: 1.7,
      key: "falloff",
      label: "Disc falloff",
      max: 12,
      min: 0.3,
      step: 0.05,
    },
    {
      default: 0.035,
      key: "thick",
      label: "Disc thickness",
      max: 1,
      min: 0.01,
      step: 0.005,
    },
    {
      default: 40,
      key: "bulge",
      label: "Core tightness",
      max: 200,
      min: 2,
      step: 1,
    },
    {
      default: 5,
      key: "core",
      label: "Core density",
      max: 20,
      min: 0,
      step: 0.1,
    },
    {
      default: 9,
      key: "turbScale",
      label: "Turbulence scale",
      max: 30,
      min: 0.5,
      step: 0.1,
    },
    {
      default: 0.35,
      key: "threshold",
      label: "Clumping",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 14,
      key: "density",
      label: "Gas density",
      max: 40,
      min: 0.1,
      step: 0.1,
    },
    {
      default: 3.5,
      key: "absorb",
      label: "Dust absorption",
      max: 20,
      min: 0,
      step: 0.1,
    },
    { default: 1.2, key: "stars", label: "Stars", max: 10, min: 0, step: 0.05 },
    {
      default: 0.5,
      key: "starDensity",
      label: "Star density",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 48,
      key: "starScale",
      label: "Star scale",
      max: 200,
      min: 5,
      step: 1,
    },
    {
      default: 0.6,
      key: "hueReach",
      label: "Hue reach",
      max: 1.5,
      min: 0.15,
      step: 0.01,
    },
    {
      default: 0.2,
      key: "pulse",
      label: "Beat depth",
      max: 3,
      min: 0,
      step: 0.01,
    },
    {
      default: 0,
      key: "breathe",
      label: "Disc breathing",
      max: 2,
      min: 0,
      step: 0.01,
    },
    {
      default: 1.1,
      key: "exposure",
      label: "Exposure",
      max: 50,
      min: 0.05,
      step: 0.05,
    },
    {
      default: 1.15,
      key: "contrast",
      label: "Contrast",
      max: 6,
      min: 0.15,
      step: 0.05,
    },
    {
      default: 1.35,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 2,
      key: "alphaGain",
      label: "Alpha gain",
      max: 15,
      min: 0.05,
      step: 0.1,
    },
    {
      default: 0.85,
      key: "fill",
      label: "Night fill",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.35,
      key: "rim",
      label: "Rim light",
      max: 3,
      min: 0,
      step: 0.015,
    },
    {
      default: 1,
      key: "edge",
      label: "Edge sharpness",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.98,
      key: "edgeFade",
      label: "Halo falloff",
      max: 3,
      min: 0.1,
      step: 0.015,
    },
  ],
  // blue into violet at rest, ice into cyan while searching, gold into rose
  // while answering
  shader: orb32Shader,
  stateColors: {
    idle: {
      core: "#fff3d6",
      deep: "#04050f",
      inner: "#7fb4ff",
      outer: "#c46bff",
      rim: "#8fb0ff",
      tint: "#ffffff",
    },
    speaking: {
      core: "#fff4c8",
      deep: "#0a0508",
      inner: "#ffa63c",
      outer: "#ff3f8e",
      rim: "#ffb98a",
      tint: "#ffffff",
    },
    thinking: {
      core: "#e6f0ff",
      deep: "#030614",
      inner: "#6fb0ff",
      outer: "#4fe3ff",
      rim: "#7fa8ff",
      tint: "#ffffff",
    },
  },
  /*
    Staged on the TILT first — each state is a different view of the disc —
    and then on the clocks and amplitudes. The tilt glides, and a tipping
    disc is the biggest, most legible motion this orb has, so the state
    change itself is the tell. The arm count and winding, the turbulence
    scale and the star scale all multiply a coordinate and are pinned.
  */
  statePresets: {
    idle: {
      absorb: 3.5,
      armSharp: 2.2,
      beat: 0.8,
      breathe: 0,
      churn: 0.25,
      contrast: 1.15,
      core: 5,
      density: 14,
      exposure: 1.1,
      pulse: 0.2,
      ragged: 3,
      saturation: 1.35,
      spin: 0.06,
      stars: 1.2,
      thick: 0.035,
      threshold: 0.35,
      tilt: 0.85,
      twinkle: 1.2,
    },
    speaking: {
      absorb: 1.6,
      armSharp: 1.8,
      beat: 4.8,
      breathe: 0.45,
      churn: 0.6,
      contrast: 1.05,
      core: 12,
      density: 18,
      exposure: 0.75,
      pulse: 1,
      ragged: 2,
      saturation: 1.6,
      spin: 0.2,
      stars: 2,
      thick: 0.04,
      threshold: 0.25,
      tilt: 1.3,
      twinkle: 2.4,
    },
    thinking: {
      absorb: 6,
      armSharp: 1,
      beat: 2.4,
      breathe: 0,
      churn: 1.6,
      contrast: 1.3,
      core: 3,
      density: 20,
      exposure: 1.05,
      pulse: 0.25,
      ragged: 8,
      saturation: 1.2,
      spin: 0.45,
      stars: 1.8,
      thick: 0.07,
      threshold: 0.5,
      tilt: 1.45,
      twinkle: 4.5,
    },
  },
  uniforms: orb32Params,
};
