import type { OrbVariant } from "@/components/orbs/canvas";
import { orb18Params, orb18Shader } from "@/components/orbs/orb-18/gpu";

export const meta = {
  description: "a crystal folded out of one eighth of space, tumbling",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-18",
  title: "ORB-18",
} as const;

export const orb18Orb: OrbVariant = {
  colors: [{ default: "#ffffff", key: "tint", label: "Tint" }],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.5,
      integrate: true,
      key: "wander",
      label: "Tumble",
      max: 5,
      min: 0,
      step: 0.02,
    },
    {
      default: 4,
      key: "camDist",
      label: "Camera distance",
      max: 50,
      min: 1,
      step: 0.3,
    },
    {
      default: 1.5,
      key: "focal",
      label: "Lens",
      max: 15,
      min: 0.15,
      step: 0.05,
    },
    {
      default: 1,
      key: "fold",
      label: "Octant fold",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 1,
      key: "crease",
      label: "Diagonal crease",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 5,
      key: "freq",
      label: "Crystal frequency",
      max: 20,
      min: 0.1,
      step: 0.05,
    },
    {
      default: 0.3,
      key: "stepScale",
      label: "Step scale",
      max: 2,
      min: 0.02,
      step: 0.01,
    },
    {
      default: 1.5,
      key: "hue",
      label: "Depth hue",
      max: 4,
      min: 0,
      step: 0.01,
    },
    {
      default: 1,
      key: "spread",
      label: "Colour spread",
      max: 3,
      min: 0,
      step: 0.02,
    },
    {
      default: 2.1,
      key: "envRadius",
      label: "Envelope radius",
      max: 15,
      min: 0.15,
      step: 0.1,
    },
    {
      default: 0.9,
      key: "envCore",
      label: "Envelope core",
      max: 1.02,
      min: 0.3,
      step: 0.01,
    },
    {
      default: 0.02,
      key: "fill",
      label: "Body fill",
      max: 20,
      min: 0,
      step: 0.01,
    },
    {
      default: 40,
      key: "stepClamp",
      label: "Step clamp",
      max: 2000,
      min: 1,
      step: 1,
    },
    {
      default: 0.004,
      key: "scatter",
      label: "Diffusion",
      max: 0.2,
      min: 0,
      step: 0.001,
    },
    {
      default: 18,
      key: "exposure",
      label: "Exposure",
      max: 500,
      min: 0.2,
      step: 0.5,
    },
    {
      default: 1.2,
      key: "contrast",
      label: "Contrast",
      max: 15,
      min: 0.15,
      step: 0.05,
    },
    {
      default: 1.25,
      key: "saturation",
      label: "Saturation",
      max: 4,
      min: 0,
      step: 0.02,
    },
    {
      default: 2,
      key: "alphaGain",
      label: "Alpha gain",
      max: 15,
      min: 0.05,
      step: 0.1,
    },
    {
      default: 1,
      key: "edge",
      label: "Edge sharpness",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.98,
      key: "edgeFade",
      label: "Halo falloff",
      max: 3,
      min: 0.1,
      step: 0.015,
    },
  ],
  // the depth ramp supplies the colour, so the tint only shifts its
  // temperature: neutral at rest, cooled while searching, warmed while
  // answering
  shader: orb18Shader,
  stateColors: {
    idle: { tint: "#ffffff" },
    speaking: { tint: "#ffc492" },
    thinking: { tint: "#9db8ff" },
  },
  /*
    Staged on the two folds, which is the only orb here where SYMMETRY is
    the mood: a crystal at rest, the mirrors relaxing open while it works,
    and locked hard shut while it answers. The tumble carries the tempo.
  */
  statePresets: {
    idle: {
      alphaGain: 2,
      crease: 1,
      exposure: 18,
      fold: 1,
      freq: 5,
      scatter: 0.004,
      wander: 0.5,
    },
    speaking: {
      alphaGain: 2.7,
      crease: 1,
      envCore: 0.49,
      exposure: 8,
      fold: 1,
      freq: 6.05,
      hue: 2,
      saturation: 2,
      scatter: 0.002,
      stepScale: 0.51,
      wander: 0.7,
    },
    thinking: {
      alphaGain: 2,
      crease: 1,
      exposure: 26,
      focal: 2.7,
      fold: 0.91,
      freq: 4.1,
      scatter: 0.02,
      stepClamp: 1200,
      wander: 1.08,
    },
  },
  uniforms: orb18Params,
};
