import type { OrbVariant } from "@/components/orbs/canvas";
import { orb12Params, orb12Shader } from "@/components/orbs/orb-12/gpu";

export const meta = {
  description:
    "a ball of glossy toy bricks, studs up — it rebuilds itself while it thinks",
  files: ["index.tsx", "meta.ts", "gpu.ts"],
  slug: "orb-12",
  title: "ORB-12",
} as const;

export const orb12Orb: OrbVariant = {
  colors: [
    { default: "#c4281c", key: "brickA", label: "Red" },
    { default: "#f2cd37", key: "brickB", label: "Yellow" },
    { default: "#1e5aa8", key: "brickC", label: "Blue" },
    { default: "#00852b", key: "brickD", label: "Green" },
    { default: "#f4f4f4", key: "brickE", label: "White" },
  ],
  key: meta.slug,
  label: meta.title,
  note: meta.description,
  params: [
    {
      default: 0.25,
      integrate: true,
      key: "spin",
      label: "Spin",
      max: 5,
      min: 0,
      step: 0.03,
    },
    { default: 0.55, key: "tilt", label: "Tilt", max: 4, min: 0, step: 0.02 },
    {
      default: 0.4,
      integrate: true,
      key: "rebuild",
      label: "Rebuild rate",
      max: 20,
      min: 0,
      step: 0.1,
    },
    {
      default: 0.07,
      key: "gap",
      label: "Missing bricks",
      max: 0.8,
      min: 0,
      step: 0.01,
    },
    { default: 18, key: "studs", label: "Studs", max: 48, min: 8, step: 1 },
    {
      default: 0.95,
      key: "radius",
      label: "Radius",
      max: 3,
      min: 0.15,
      step: 0.015,
    },
    {
      default: 0.35,
      key: "patch",
      label: "Colour patches",
      max: 1,
      min: 0,
      step: 0.01,
    },
    {
      default: 0.85,
      key: "stud",
      label: "Stud relief",
      max: 1,
      min: 0,
      step: 0.01,
    },
    { default: 0.6, key: "seam", label: "Seams", max: 1, min: 0, step: 0.01 },
    { default: 1, key: "gloss", label: "Gloss", max: 3, min: 0, step: 0.02 },
    {
      default: 1,
      key: "light",
      label: "Key light",
      max: 3,
      min: 0,
      step: 0.015,
    },
    { default: 1, key: "gain", label: "Gain", max: 5, min: 0.05, step: 0.05 },
    {
      default: 1,
      key: "contrast",
      label: "Contrast",
      max: 10,
      min: 0.15,
      step: 0.05,
    },
  ],
  shader: orb12Shader,
  stateColors: {
    speaking: {
      brickA: "#ff3b6b",
      brickB: "#ffc93c",
      brickC: "#21d4fd",
      brickD: "#7af5a0",
      brickE: "#ffffff",
    },
  },

  statePresets: {
    idle: {
      gain: 1,
      gap: 0.07,
      gloss: 1,
      light: 1,
      rebuild: 0.4,
      spin: 0.25,
    },
    speaking: {
      contrast: 0.95,
      gain: 1.25,
      gap: 0,
      gloss: 2.4,
      light: 1.35,
      rebuild: 0.5,
      seam: 0.3,
      spin: 1.6,
      stud: 0.6,
      tilt: 0.42,
    },
    thinking: {
      contrast: 1.05,
      gain: 1.05,
      gap: 0.55,
      gloss: 0.55,
      light: 1.15,
      rebuild: 9,
      seam: 0.95,
      spin: 0.03,
      stud: 1,
      tilt: 0.9,
    },
  },
  uniforms: orb12Params,
};
